version: '3.8'
services:
  redis:
    image: redis
    ports:
      - "127.0.0.1:6379:6379"
    user: "redis:redis"
  postgres:
    image: postgres
    ports:
      - "127.0.0.1:5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: outline
    user: "postgres:postgres"
outline:
    image: outlinewiki/outline
    ports:
      - "3000:3000"  # Доступен на порту 3000
    environment:
      NODE_ENV: production
      DATABASE_URL: postgres://user:pass@postgres:5432/outline
      PGSSLMODE: disable  # Отключение SSL для подключения к базе данных
      SECRET_KEY: 6VwRe7zze93iq8iZsIlBa+OFj6xAdxNFdFhoQ/pT+TE=
      UTILS_SECRET: lyADEkuvtwChbr8rAwSHLFmxt4UHCXFcBQUvYW1Z03U=
      URL: http://176.124.214.113  # Изменено на HTTPS
      REDIS_URL: redis://redis:6379
      FILE_STORAGE: local
      FILE_STORAGE_LOCAL_ROOT_DIR: /var/lib/outline/data
      FILE_STORAGE_UPLOAD_MAX_SIZE: 262144000
    depends_on:
      - postgres
      - redis
    volumes:
      - outline_data:/var/lib/outline/data
